apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWpreApPREV5TWpOYUZ3MDBNekF4TWpreE9ERXlNak5hTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFERzZ5SUJhdFJhMFhjMDBnSmlZQ1pwTDlia3ByVE1zbFAxME1PdkRoK2JKdm4vYnd5OQp6TkhGdjlBeWptSkxxb25HcENEYytMUXdLUVR2VUJQZlQwdldDUGVsdjhlVG12MU5SMExQNXRxdUE3UmRuRG42CkQxbEhWdDBlTHEwZjYyekIrM3k4djl0YUR5c1lHZEhDRkQ4c0hRUDZXK09XOTlTUlVNOTFoOGdKR29vejJQcmcKRU4vZUlRS3gzdjB0a2x2Y2VFT2NqWWp0YmF3eWYxRGpPYXo1L0dLYWljNEdReStnYnVJOVgrdVR0OUtKL283OQpoOWlIdDZ5NlF3NEd2Nlhxd1JvdmxXdElSNzR3aGJHMkJWQUV2R1BGQnhIQy8rNjdjNlJLb1YzM01mc0QzOHlwCnViS2YvSlNKb3BxVFZOR0pKQUVPbkg3TjBXNlEwem5pSlRnbEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFWZjk4emZDL0FYWDQvY1IyVQpVMloxWENGN3N6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFSYnVLSDdMN2Z6Y0VtcmZMYjd5Rkp2aUo1bjF3Cm9LODZWRlA4VERXWHdpOGw5WGt6aklSdmFONjN2dFVETkJmR1VBeGZDb2lZWHFWbFROZWtZYU1WVlVIZk8ra3oKYnlBb1VlRUJQeXAzMnhoRVZQb0pjK2pkL0JZUVc2clFsWC9tMHNuMXNZN2hIYWZiZnN1bWtWT0R6Ynk5WE9INwpCZEtQejJaMmZic2RYUmxka2dnRk1GMEc1QkMwYWNSK0xzN29QaWgwWUNDaWJxUGVWQWpQVE9WY2N1UEtJWVduCk5ieXJDcVYvRERwVjFzK2ZTeVdaQi9CUHhheXBrNU5icitYdkJubFZTbHNHY3FFcW12S04xVWgyaG51N3lnWGkKTVJ6MjlXc3NldVBhcHFRdTdXT1BRTndjVFZ0RW1hTDJhVndvSXFPdXd0akxlK1MrajVtWlZlZCtLdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://59135a4b-7dea-4d03-9187-d9466dbfd17a.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_b539be9cd4e6753453152fdcb7b12c1ca0dac10be501d19ab00e7c7318e7b953
